#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define FAMOS_TOTAL_INTERRUPTS 512

// 100 MB heap size
#define FAMOS_HEAP_SIZE_BYTES 104857600
#define FAMOS_HEAP_BLOCK_SIZE 4096
#define FAMOS_HEAP_ADDRESS 0x01000000 
#define FAMOS_HEAP_TABLE_ADDRESS 0x00007E00 

#define FAMOS_SECTOR_SIZE 512 

#define FAMOS_MAX_FILESYSTEMS 12 
#define FAMOS_MAX_FILE_DESCRIPTORS 512 

#define FAMOS_MAX_PATH 108 

#define FAMOS_TOTAL_GDT_SEGMENTS 6 

#define FAMOS_PROGRAM_VIRTUAL_ADDRESS 0x400000 
#define FAMOS_USER_PROGRAM_STACK_SIZE 1024 * 16 
#define FAMOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000 
#define FAMOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END FAMOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - FAMOS_USER_PROGRAM_STACK_SIZE 

#define USER_DATA_SEGMENT 0x23 
#define USER_CODE_SEGMENT 0x1b 


#endif